### ISSUE TITLE
Final Lab- Part 1, Step 7

### ISSUE THREAD

**Issue by shumway99** [Watts-College/paf-514-template#101]
Hey @castower or anyone else who is up and working on this :) 

I have a question on part 7. Again, I'm sure I'm probably just approaching the problem all wrong and it's a simple solution, but to create the sample, here is the code I am using: 

get_study_sample <- function(x){
  academic.units <- 
c("CISA-Intrdisp Hum & Comm", "CISA-Science & Mathmatics", 
"College of Health Solutions MS", "College of Health Solutions NT", 
"College of Health Solutions SH", "College Of Law", "English", "Hugh Downs School Of Comm", 
"Humanities Arts & Cultural", "Journalism & Mass Comm", "Ldrshp and Integrative Studies", 
"Math & Natural Sciences Div", "MDT Music", "Physics Department", 
"Psychology", "Sch Biological & Hlth Sys Engr", "Sch Compt Infor & Dec Sys Engr", 
"Sch Elect Comptr & Energy Engr", "Sch Engr Matter Trnsprt Energy", 
"Sch Future of Innov in Society", "Sch Sustain Engr & Built Envrn", 
"School Of Art", "School of Criminology & Crim J", "School Of Earth & Space Explor", 
"School of Geog Sci & Urban Pln", "School of Math & Stat Sciences", 
"School of Molecular Sciences", "School of Politics & Global St", 
"School Of Public Affairs", "School of Social Transform", "School Of Social Work", 
"SHPRS History Faculty", "Social & Behavioral Sciences", "Sols Administration & Faculty", 
"SOS Faculty & Researchers", "The Design School", "The Sanford School", 
"WPC Accountancy", "WPC Economics", "WPC Information Systems", 
"WPC Management", "WPC Supply Chain Management")
  filtered_titles <- filter(d$title != "" & ! is.na(d$title))
  filter_by_academic_units <- filter(d$Department.Description %in% academic.units)
  arranged_titles <- arrange(filter_by_academic_units, filtered_titles)
  return(study_sample)
}
study_sample <- get_study_sample(d)

When I try to run this, however, I keep getting the following error that I have tried to google and have zero clue how to fix: Error in UseMethod("filter"): no applicable method for 'filter' applied to an object of class "logical". 
From what I can see on google, it looks like since Department.Description or academic.units are just character class instead of factor class, it won't let me filter with them? But that doesn't make any sense because it's literally how it shows to do it in the assignment haha, that's why I'm thinking that I'm probably just approaching this whole step in the wrong way. 

Any help on this step would be much appreciated!

**Comment by shumway99** [comment]
And also as a follow up question to that, are Steps 8 and 9 only using our sample, or the entire dataset?

**Comment by swest235** [comment]
@shumway99 a few things:
1) If at this step your title column should be an integer (remember this is how R stores factors internally). You can check it with class(d$title) but the add_titles() makes title a factor, so make sure that function is working properly. It should end with:

   d$title <- factor( title, 
                     levels=c("Full Professor","Associate Professor",
                              "Assistant Professor","Teaching Faculty",
                              "Researcher" ) )
                              
2) I did have an issue with mine similarly and found out it was because I tried to apply filter() to the column, but filter() must be applied to the data frame. I switched to piping my steps in the function and it worked fine. 

3) Lastly, you shouldn't include your academic units object list inside the function, rather have it outside so it will be referenceable outside of the function (remember anything defined in the function isn't available in the environment outside of the function). I can't recall if there are other references to academic.units outside of that function in the demo itself, but it seems more rational to me to keep it outside in case you do. If you do need it elsewhere and it is in the function you'll get an error object not found.

**Comment by shumway99** [comment]
Wait so should title be a factor or an integer at this stage? Mine is a factor.

**Comment by swest235** [comment]
@shumway99 sorry, I should've clarified, yes. d$title should be a factor (R internally codes factors as an integer). Assuming you ran the add_titles() earlier in your document your titles should be factors. If you run class(d$title) it'll show factor, if  you run typeof(d$title) it will show integer - how R sees it. Either way, to fix your error you'll want to use pipe operators. The error you're experiencing is because filter() can only be applied to the data frame, not just a column within the data frame - at least that was the conclusion I was able to come to when I had that error. 

sample.d <- d  %>% filter (...) %>% filter(...) then make your sample. 

Does that make sense?

**Comment by shumway99** [comment]
No worries, thanks for clarifying!

And yes, that makes sense, but my other problem is that I thought we were supposed to be making this sample in a function? Like I had above, it would be something like: 

get_study_sample <- function(x){all the stuff to filter it out and make the sample in here}

Do we not have to do that?

Like you said, if you pipe the filter function, then it works just fine- I only started having trouble with filter() when I tried to put it in another function like above, and then piping it isn't fixing it. I'm not sure if I'm making any sense haha

I guess my main question is, do we have to make a study_sample function like I think we do? Or am I trippin haha

**Comment by shumway99** [comment]
Thanks for all your help @swest235!

**Comment by shumway99** [comment]
Or is piping it like you showed making it a function? Clearly I don't know R well enough to even have the basic definitions of things down *face palm*

**Comment by swest235** [comment]
@shumway99 just use pipe operators within the function itself

**Comment by castower** [comment]
Yes, great explanation @swest235 !

**Comment by castower** [comment]
@shumway99 For steps 8 and 9 you will want to use your entire data set.

**Comment by shumway99** [comment]
Okay I have just been on the struggle bus over here haha! I thought that piping wasn't working within the function, but it's because I didn't start with d %>% at the top! 

Thank you for all your help!!!
