### ISSUE TITLE
R Package

### ISSUE THREAD

**Issue by mbrentli** [Watts-College/paf-514-template#13]
I'm feeling very overwhelmed and confused about this R package.  Exactly which functions are we supposed to be including in this package?  The instructions say that its from Labs 1 and 2, but that's a lot of different versions of the game - I'm confused...do  we do all the different versions?   

I'm up to section 1.2.3 "document your functions".  Are we supposed to create separate rmd files for each function individually and document them individually?

I have no idea how to move on from here and the materials and/or googling is not helping.

**Comment by lecy** [comment]
You should have a link to a template R file that will get you started.

https://watts-college.github.io/paf-514-template/labs/create-r-package.html

https://www.dropbox.com/s/u8k1co2bb7eldzj/monty-hall-problem.R?dl=1

You can use the solutions shared from Lab 01. It’s less about which version of the functions you use, and more about how you convert them into the package.

it’s not meant to be a challenging exercise - just an introduction to how packages are made because it’s useful background knowledge that can be beneficial on the job market. You have all of the steps laid out. But there is a bit of nuance in some of the instructions. 

You are using an R script, not RMD files. When you call the function to document() the package it converts R functions into RD (R documentation) files. It’s a slightly different knitting process.

**Comment by mbrentli** [comment]
Thanks, I've written the documentation, and placed the .R file into the R folder in the montyhall folder, and am trying to set the working directory, but it's not working.  

> setwd( "montyhall" )
Error in setwd("montyhall") : cannot change working directory

If I put the entire filepath:
> setwd("C:\Users\mbren\OneDrive\Desktop\PAF_514\montyhall")
Error: '\U' used without hex digits in character string starting ""C:\U"

Googling the issue says that the error is caused by a filepath that doesn't exist, but I have quadruple checked and am copy-pasting the file path directly.

**Comment by mbrentli** [comment]
Nevermind, I figured it out.  Apparently the WD was set to that already.

**Comment by lecy** [comment]
R uses Linux style filepaths, so you need to switch the backslashes to forward slashes when entering the full path:

```
setwd("C:\Users\mbren\OneDrive\Desktop\PAF_514\montyhall")
```
