### ISSUE TITLE
Lab 04-Stemming Issue

### ISSUE THREAD

**Issue by DrKBoucher** [Watts-College/paf-514-template#19]
When I try to complete the stemming step for this week's lab, I get the following message:

Warning message:
'stem' is deprecated; use dfm_wordstem() instead 

I looked this up and discovered that we should use tokens_wordstem or dfm_wordstem in its place. I am not sure how to apply either of those because I get the following errors:

> dfm_wordstem( tokens ) %>% topfeatures( )
Error: dfm_wordstem() only works on dfm objects.

> tokens_wordstem( tokens ) %>% topfeatures( )
Error: topfeatures() only works on dfm objects.

Does anyone know how to appropriately apply either of these alternatives correctly?

**Comment by lecy** [comment]
This is a good example of **dependencies** in open source ecosystems (and related to concepts discussed in your last R package assignment): 

https://watts-college.github.io/paf-514-template/lectures/function-conflicts/

It appears that quanteda has refactored some code and renamed some functions. All of the other packages that rely on quanteda, or analytical scripts that use the package (like this tutorial) will break because of the changes. 

Next semester you will learn how to use **renv** to create a stable R environment (if you loaded a previous version of quanteda the examples would work fine - renv gives you control over which version is loaded). 

For this case, let me look through the lab and figure out which commands need to be updated. I'll share an update at the review session, if not before.

**Comment by lecy** [comment]
Updated version: 

```r
# old 

tokens %>% 
  dfm( stem=T ) %>% 
  topfeatures()

# new version

tokens %>%
  dfm() %>% 
  dfm_wordstem() %>% 
  topfeatures()

```
