### ISSUE TITLE
Installing quanteda package error

### ISSUE THREAD

**Issue by ashleycc33** [Watts-College/paf-514-template#20]
Hi there,
I tried installing the quanteda package, and it worked, but when I tried bringing up the library, I got this error:
Error: package or namespace load failed for ‘quanteda’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
namespace ‘Matrix’ 1.4-1 is being loaded, but >= 1.5.0 is required

**Comment by lecy** [comment]
Close R. Reopen and install Matrix.

**Comment by ashleycc33** [comment]
That worked, thank you!

**Comment by lecy** [comment]
To link it back to the package-building exercise, this is another example of dependencies. The functions in Matrix probably changed with version 1.5.0, so previous versions were no longer compatible. When you create a package you declare dependencies in the DESCRIPTION file - those are installed when people install your package. You can also specify versions in this file as well (the utils example below): 

```r
# IN DESCRIPTION FILE
Depends:
    qtl 
Imports:
    jsonlite,
    utils (>= 1.30-4)
Suggests:
    knitr,
    devtools
```

**Comment by ashleycc33** [comment]
Gotcha. I was also getting this question when initially installing:
Do you want to install from sources the package which needs compilations? (Yes/no/cancel)

I was saying yes, but because I wasn't really reading it, and it didn't work. Then I wrote "no" and it worked.

**Comment by lecy** [comment]
> Do you want to install from sources the package which needs compilations? (Yes/no/cancel)

Packages that are written entirely in R usually to not need to be compiled. Some packages have external dependencies (libraries outside of R) or are written in C++ or another general purpose language in order to run faster. 

If you need to compile packages, you typically need [RTools](https://cran.r-project.org/bin/windows/Rtools/). 

https://clanfear.github.io/CSSS508/docs/compiling.html#:~:text=The%20newest%20versions%20of%20R,small%20amount%20of%20additional%20setup.
