### ISSUE TITLE
R Package-man folder empty

### ISSUE THREAD

**Issue by jacobmorgan05** [Watts-College/paf-514-template#47]
Hi Jesse,

I'm trying to finish up the r package project and the script is documented in line with the example provided. After I run:

```r
setwd( "montyhall" )
getwd()
devtools::document()
``` 
I get the following in the console:
![image](https://github.com/Watts-College/paf-514-template/assets/110744916/001903aa-328a-49b7-a6a4-dea3ff3a2e1f)

My directory looks like:
![image](https://github.com/Watts-College/paf-514-template/assets/110744916/cccee347-a604-4771-a8a3-422d6837d15d)

but the man folder is empty. I've tried googling and looking at other students' questions but cannot figure out what I am missing.

**Comment by lecy** [comment]
You are doing this in R Studio?

It looks like a prompt in the console, not an error message. What happens if you select YES? 

I’m wondering about the error line, “updating loaded package”. Did you already install montyhall? If so, try uninstalling it first. See the section on removing a package in the instructions.

I’m also wondering why it’s highlighting the DESCRIPTION file. Did you fill out the required information there? 

The only other thing I can think of is improperly formatted Roxygen, which might cause an error in how the documentation is rendered. But you usually get an error message if that happens. 

Start with those ideas and if it’s not working email me your R script.

**Comment by lecy** [comment]
If others are running into similar problems, I have created an annotated script with all of the steps needed to create the package. It makes the directory levels and file management explicit for those that were getting confused about which files belong where.

https://raw.githubusercontent.com/Watts-College/paf-514-template/main/labs/annotated-pkg-creation.R

 I know a couple of students were trying to combine package code (functions in your R script) with package creation code (the steps outlines in the instructions). 

These are two completely separate scripts. Once you get comfortable creating a package you might not use a package creation script. If you want to save your steps, though, you can always add a "notes" folder (or any other folder name that is not a protected name in the R package environment - mainly R, man, and data). 

```r
# at setup
dir.create( "pkg" )
setwd( "pkg" )
root.dir <- getwd() 

  #   >>> put your R scripts in "pkg" folder
  #       check to see if they are there

  #   documents 
  #   ├─ pkg                         <<< you are here      
  #   │  ├─ monty-hall-pkg.R  
  #   │  ├─ annotated-pkg-creation.R
  
###   <  SAVE CREATE PACKAGE SCRIPT  >
###   --------------------------------
###   if you want to save these steps 
###   in case you need to update the 
###   package sometime in the future:

montyhall.folder <- paste0( root.dir, "/montyhall" )
setwd( montyhall.folder )
dir.create( "notes" )

  #   save script first if you made changes, then: 

mhp.path <- paste0( root.dir, "/annotated-pkg-creation.R" )
notes.folder <- paste0( root.dir, "/montyhall/notes/annotated-pkg-creation.R" )
file.copy( from=mhp.path, to=notes.folder )

  #   documents 
  #   ├─ pkg           
  #   │  ├─ montyhall  
  #   │     ├─ notes    
  #   │        ├─ annotated-pkg-creation.R    <<<
```
