### ISSUE TITLE
Lab-06 Part 2 Step 5

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-514-template#55]
@lecy Hi! 

I am just a little bit confused on the last step for Part 2.

Instructions: "Go into settings and activate your GitHub page for this repository. Do not select a template.

You should now be able to view your HTML resume online.

Update the description section at the top right of your GitHub repo and add the link to your resume."

I cloned the repository and I have it on Github Desktop, but I do not see it on my Github page. For these instructions are we doing these steps from Github Desktop or Github?

**Comment by lecy** [comment]
Please look through the updated instructions on the live GitHub page:

For this assignment you will need to clone a version Nick Strayer's CV project that has been archived on the DS4PS site: 

[CV Project on GitHub](https://github.com/DS4PS/cv)

Start by copying files to a copy on your own GitHub account by selecting **Use this template >> Create a new repository >> name it "cv"**. 

![image](https://github.com/Watts-College/paf-514-template/assets/1209099/6bf28753-b34f-4da0-bb9d-d2405598e6cd)

You now have a copy of the project files in a new project repo on your personal account. 

To sync them to your computer for editing, clone YOUR VERSION of the cv site (the one you just added to your GitHub account). In the GitHub desktop application select **File >> Clone >> URL** then type in the new project URL: 

https://github.com/YOUR_GITHUB_ID_HERE/cv

This step copies the files to your computer and also give you permission to send updated files back to your project repo with a "commit >> push" command. 

*Note, since Nick's CV project is actively being developed we are using a version on DS4PS is frozen for pedagogical purposes. You are encouraged to visit his CV project repo to see all of the new features he has added beyond what you have seen on this project.*
