### ISSUE TITLE
Lab Part 3 - Utils.R

### ISSUE THREAD

**Issue by acampbell7** [Watts-College/paf-514-template#58]
@lecy hi professor, per our conversation earlier, this is the issue im exhibiting:

when in salary-report.rmd mu utils.R file is uploading all graphs. I believe you stated in utils.R file should just be the functions for reusable code, to use later on. I just want to verify I remove specific infromation (such as the graphs in utils files)   

for example this is populating when I run source("utils.R")
 
<img width="935" alt="Screenshot 2024-02-19 at 8 59 47 PM" src="https://github.com/Watts-College/paf-514-template/assets/133538574/af13b5b7-e030-480b-9627-1304cefeb1e0">

I think I got confused and added all variables as well in: 
"The utils.R File
Once all of your functions are working properly copy them all into the utils.R script." end of part 1 example. 

Thanks in advance :)

**Comment by lecy** [comment]
You can think about your **utilities** file **utils.R** as your local library of functions. It is a more informal version of an R package - a library of functions without the formal documentation. 

As such, you load your utilities function in the same place you load all of your other libraries: 

```r
library( dplyr )
source( "utils.R" )
```

Note that the intended side-effect of sourcing the file, especially inside of a report template, should be to make available all of the custom functions you created so that you can use them in your RMD doc. You do not want the utilities file, however, to execute a bunch of other things that generate output or change data in your environment. 

Make sure you ONLY include functions inside of utils.R, and do not include extra code that executes operations or runs examples. I will always include a code snipped to test the function, but I will comment it out so that it's not executed when the file is sourced. 

```r
dollarize <- function(x) 
{ paste0("$", format( round( x, 0 ), big.mark="," ) ) }

#  x <- c(100, 1000, 10000, 1000000 )
#  dollarize(x)
#  [1] "$      100" "$    1,000" "$   10,000" "$1,000,000"
```

Note that the package version would alternatively include this test code as part of the `@examples` roxygen section: 

```r
#' @examples
#'   x <- c(100, 1000, 10000, 1000000 )
#'   dollarize(x)
#' @export
dollarize <- function(x) 
{ paste0("$", format( round( x, 0 ), big.mark="," ) ) }
```
