### ISSUE TITLE
Final Project Build Graph Function

### ISSUE THREAD

**Issue by kphart2** [Watts-College/paf-514-template#63]
Hello, I am getting an error message in my function-demo.rmd when I am trying to test the build graph function in Pt 1 Step 9. The same error message is also popping up in Pt 2 when trying to add the loop.

```r
d %>%  
  filter( Department.Description == "Psychology" ) %>% 
  create_salary_table( ) %>% 
  build_graph( unit="Psychology" )`

`Error in `filter()`:
ℹ In argument: `!is.na(title) & title != ""`.
Caused by error in `title != ""`:
! comparison (!=) is possible only for atomic and list types
Backtrace:
  1. ... %>% build_graph(unit = "Psychology")
 11. dplyr:::filter.data.frame(., !is.na(title) & title != "")
 12. dplyr:::filter_rows(.data, dots, by)
 13. dplyr:::filter_eval(...)
 15. mask$eval_all_filter(dots, env_filter)
 16. dplyr (local) eval()
Error in filter(., !is.na(title) & title != "") : 
Caused by error in `title != ""`:
! comparison (!=) is possible only for atomic and list types
```

**Comment by lecy** [comment]
For your Step 2 error see the [batch processing loop with 2019 data](#61) thread.

For the Step 9 error, the cause will be the same thing - you are applying some filter to your data that results in an empty data frame (columns but no rows). So some of your code prior to this step is not working properly. You can confirm this by previewing your data frame right before you execute these lines: 

```r
d %>%  
  filter( Department.Description == "Psychology" ) %>% 
  create_salary_table( ) %>% 
  build_graph( unit="Psychology" )`
```

For discussion board purposes it's helpful to provide a preview of your data at the point the error is generated since you are doing a of data wrangling prior. You can share the data frame with your example using: 

```r
d %>% head() %>% dput()   # prints first 6 rows of the df in a format that can be shared in a discussion board
```

```r
d <- 
structure(list(Calendar.Year = c(2019L, 2019L, 2019L, 2019L, 
2019L, 2019L), Full.Name = c("Abadjivor,Enyah", "Abbas,James", 
"Abbaszadegan,Morteza", "Abbe,Scott", "Abbl,Norma", "Abbott,David"
), Job.Description = c("Coordinator", "Assoc Professor", "Professor", 
"Tech Support Analyst Coord", "Sr HR Consultant", "Assoc Professor"
), Department.Description = c("Research Division 2 Tempe", "Sch Biological & Hlth Sys Engr", 
"Sch Sustain Engr & Built Envrn", "Engineering Technical Services", 
"HR Partners", "Shesc"), Salary = c("$45,195.00", "$101,795.00", 
"$143,625.00", "$95,560.00", "$86,806.00", "$86,188.00"), FTE = c(100L, 
100L, 100L, 100L, 100L, 100L), X = c("NOTE: This data is public record salary data of Arizona State University employees, compiled by The State Press. Last updated Dec. 5, 2017. View the numbers in a searchable database at http://www.statepress.com/article/2017/04/spinvestigative-salary-database", 
"", "", "", "", "")), row.names = c(NA, 6L), class = "data.frame")
```

**Comment by kphart2** [comment]
Thank you. I think I fixed the that issue but now am getting this error:

`Error in plot.window(xlim = c(40000 - 10000, xmax), ylim = c(0, ymax +  : 
  need finite 'xlim' values`

Here is my data:

`structure(list(first.name = c("Barry", "Brooks", "Eva", "Ian", 
"Jewell", "Claire"), Calendar.Year = c(2020L, 2020L, 2020L, 2020L, 
2020L, 2020L), Full.Name = c("Maid, Barry", "Simpson, Brooks", 
"Brumberger, Eva", "Moulton, Ian", "Rhodes, Jewell", "Lauer, Claire"
), Job.Description = c("Professor", "Professor", "Professor", 
"Professor", "Professor", "Assoc Professor"), Department.Description = c("CISA-Intrdisp Hum & Comm", 
"CISA-Intrdisp Hum & Comm", "CISA-Intrdisp Hum & Comm", "CISA-Intrdisp Hum & Comm", 
"CISA-Intrdisp Hum & Comm", "CISA-Intrdisp Hum & Comm"), Salary = c("$54,050.00", 
"$145,610.00", "$106,350.00", "$100,000.00", "$297,000.00", "$90,150.00"
), FTE = c(50L, 100L, 100L, 100L, 100L, 100L), salary = c(108100, 
145610, 106350, 1e+05, 297000, 90150), gender = structure(c(1L, 
1L, 2L, 1L, 2L, 2L), levels = c("male", "female", "uncoded"), class = "factor"), 
    title = structure(c(1L, 1L, 1L, 1L, 1L, 2L), levels = c("Full Professor", 
    "Associate Professor", "Assistant Professor", "Teaching Faculty", 
    "Researcher"), class = "factor")), row.names = c(NA, 6L), class = "data.frame")`

**Comment by lecy** [comment]
Your new salary variable looks fine and I see you were able to integrate the gender attribute.  

The error you encounter is: 

```r
xlim = c(40000 - 10000, xmax):  need finite 'xlim' values
```

Which suggests that you may have an infinite value or a NaN (not a number) in your salary. That can be caused by dividing by zero or another mathematical error. You can check by inspecting salary: 

```r
summary( d$salary )
```

It is almost certainly something introduced during your data wrangling steps but you are not showing any of those steps here nor the code creating the error. Was it the specific example above with the Psychology department, or the loop that you mentioned before? 

Can you share a little more about your data recipe? What is the output here prior to trying to graph the table? 

```r
d %>%  
  filter( Department.Description == "Psychology" ) %>% 
  create_salary_table( ) 
```

**Comment by kphart2** [comment]
Here is what I get when I inspect salary:

summary(d$salary)
Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10504   57464   90561   98322  117731  436101 

I am getting the xlim error at the psychology department example and at the loop. And also when trying to run the batch file. 

I can post more of my code but am unsure which parts would be most helpful for you to look at.

**Comment by lecy** [comment]
What does this produce? 

```r
d %>%  
  filter( Department.Description == "Psychology" ) %>% 
  create_salary_table( )
```
