### ISSUE TITLE
Module 1 Monty Hall Problem Coding Issue In Step Three

### ISSUE THREAD

**Issue by tnt2501** [Watts-College/paf-514-template#65]
Hi @castower, I am have been constantly having an issue with my code in Step 3 and I can not seem to find a way around it!

```{r}
open_goat_door <- function(game, a.pick) 
{
  doors <- c(1, 2, 3)
  
  remaining_doors <- setdiff(doors, a.pick)
  
  goat_doors <- which(game == "goat")
      
  possible_door <- intersect(remaining_doors, goat_doors)
  
  opened_door <- sample(possible_door, size = 1)
  
  return(opened_door)
  
}

```

When proceeding with the following code, possible_doors seems to be giving the correct values, but when I take the sample of possible_doors I keep getting wrong values. (Such as the same value as a.pick or the same door the car is behind). This makes no sense to me as when I return possible_doors everything looks to be correct. I even tried reversing it all to return "car" instead of "goat", but had the same problem. 
Do you have any insight for me that could help me with my problem? Thanks in advance!

**Comment by castower** [comment]
Hello @tnt2501,

This is a good question! According to the documentation for the sample() function, if x has a length of 1 then the function treats the input as a range of 1:x. So for example, if possible_door equals 2 then the sample function will return 1 or 2: [](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/sample ) where as if possible_door has 2 & 3 then it will return 2 or 3.

In order to resolve this, you can add an if statement to use sample only if you have two possible doors; otherwise just assign the door:

```  
if (length(possible_door) > 1) {
  opened_door <- sample(c(possible_door), size = 1)
} else {
  opened_door <- possible_door
}
```

Let me know if you have any other questions!
