### ISSUE TITLE
Lab 1 - Step 3

### ISSUE THREAD

**Issue by swest235** [Watts-College/paf-514-template#66]
@castower I believe I've coded the open_goat_door correctly; however, the host selected door is the door with the car, not the goat. I've rerun it several times and it also is selecting the same door as the contestant on occasion. Seems like I'm way off track on what it should be. 

Can you help point me in the right direction here? 

![image](https://github.com/user-attachments/assets/27492c1c-530f-4d66-a22a-bd3c5e78d0a7)

```
##Lab 1: Control Structures

###Function 1: Game Setup (create.game)

Psuedocode: 
1. Create a vector with 3 doors (goat, goat, car)
2. Randomize positions for each game
3. Return new game

Code:
```{r}
create.game <- function()
{
  a.game <- sample (x = c("goat", "goat", "car"), size = 3, replace = F)
  return(a.game)
}
```

Test Code: 
```{r}
create.game()
create.game()
create.game()
```

###Function 2: Contestant Selection (select.door)

Psuedocode: 
1. Create vector for door numbers (1, 2, 3)
2. Select a RANDOM door
3. Return randomly selected door

```{r}
select.door <- function()
{
  doors <- c(1, 2, 3)
  a.pick <- sample(1:3, size =1, replace = F)
  return(a.pick)
}
```

Test Code:
```{r}
select.door()

select.door()

select.door()

select.door()
```

###Function 3: Reveal Goat Door

Psuedocode:
1. Build off of previous create.game & select_door functions. 
2. Create parameters for host to select door (must be goat, can't be contestants selection)
3. Select Door

Code: 
```{r}
open_goat_door <- function(game, a.pick)
{
  host.options <- game[-a.pick]
  host.pick <- sample(which(host.options == "goat"), size = 1, replace = F)
  return (host.pick)
}
```

Test Code: 
```{r}
this.game <- create.game()
this.game
my.initial.pick <- select.door()
my.initial.pick
open_goat_door(this.game, my.initial.pick)

```

**Comment by KaytieS** [comment]
Hi @swest235 I was actually having the same issue and tried to rewrite the code in many different ways to fix it and still kept running into the same problem. I finally found out that the problem is that the possible doors for the host to choose from are re-indexing after taking out the contestant’s pick. Going by the names used in your code, the host.options vector is becoming a vector of 1 and 2 since you removed one door choice from the vector, so now “car” is in the position of 1 and “goat” is in the position of 2. So it is correct for returning 2 since that is the position of the goat door in the new vector but based on the initial vector, 2 is the position that the car was in. Hope that explanation made sense, here is the code I used to solve the issue: 

`open_goat_door <- function(this.game, my.initial.pick) {

  possible.doors <- which(this.game == "goat" & (1:3) != my.initial.pick)
  
  if (length(possible.doors) > 1) {
    opened.door <- sample(possible.doors, size = 1)
  } else {
    opened.door <- possible.doors
  }
  
  return(opened.door)
}

`

**Comment by castower** [comment]
Hello @swest235,

Great question!

It's important to note that you need to focus on the door **_numbers_** as your first step, then you can select from the remaining doors:

# Find all goat door options
goat_doors <- which(game == "goat")

# Find all goat doors that do not match pick
goat_doors <- goat_doors[! goat_doors %in% c(a.pick)]

# Select door that has goat
if (game[goat_doors[1]] == "goat") {
  host.pick <- goat_doors[1]
} else {
  host.pick <- goat_doors[2]
}

Let me know if you have any other questions!

**Comment by swest235** [comment]
@castower @KaytieS 

Thank you both for your help. I was able to get everything finished with the helpful clarification.
