### ISSUE TITLE
Lab03 - Q1

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/paf-514-template#78]
I understand how to grab all the titles that have numbers in them (e.g., "1" or "2"):

grep( "^[0-9]", d$title, value = TRUE, ignore.case = TRUE) %>%  head(20)

But how do I do this for any written number (e.g., "three," "seventy-two," "ten")? 

This is coming up because one of the title examples that is provided is: 

"**Six** Recommendations for Aspiring Data Scientists"

**Comment by KaytieS** [comment]
@castower I am also having problems with the power list category. There are instances in which the number is spelled out, so would we have to include a list of spelled out numbers within our code? Such as:

`power_lists <- grepl("^(\\d+|one|two|three|four|five|six|seven|eight|nine|ten)\\b", d$title, ignore.case = TRUE)
`

Also, there are some titles that include number that I do not think fit into the power list category, so do we need to filter for more than just a number in the title? At first I thought maybe filtering for only titles that start with a number would work but then I realized some titles start with a word like “The” and also I saw some titles that start with a number that don’t seem to fit in the category.

**Comment by lecy** [comment]
You are working with rule-based classification. Your grepl() regular expression is a rule (classify any title that starts with a number as belonging to the "power list" category). Rule-based classification will always be imperfect because of EDGE CASES. For example: 

*   cases that might start with a number but are not actually a power list (false positives)
*   cases that should be included in the power list but are hard to capture (titles that start with an uncommon written number like "seventy-two"). 

When implementing rule-based classifiers you can think about the quality of your solution as a confusion matrix. On the left the 1 means the title actually belongs to the power list category. On the right the 1 means that it was identified by your regular expression as being part of the power list. Here 56 cases were actually in the group and identified as part of the group by the classifier (true positive cell). Conversely you hope that all of the non-power list titles fall into the {0,0} cell (true negative cell). False positives would be {actual=0, predicted=1} and false negatives are {actual=1, predicted=0}. 

![How to Create a Confusion Matrix in R (Step-by-Step)](https://www.statology.org/wp-content/uploads/2021/04/confusionR1.png)

Because of edge cases your classifier will not be perfect, which is OK. If you have a balance of false positives and false negatives like the example below then you are just introducing some measurement error to the analysis, not bias. 

The goal in using regex is to write **generalizable expressions** that correctly classify 80-90% of the cases. The other 10-20% of the cases represent edge cases that can be addressed by adding additional \*\*overly specific\*\* rules written for a small number of edge cases (not generalizable expressions).  

Draft your expressions, then inspect your data. In skimming 100 rows does it look like you are identifying most of the cases that should be coded as power lists without creating a lot of false positives? Or do you see that your expression is failing to identify a lot of cases? 

The bar is demonstrating a procedural understanding of regular expressions. As a rule of thumb, you can ignore most of the edge cases in preliminary analysis as long as your expressions have a true positive + true negative rate above 80%. 

ASIDE: 

For preliminary analysis or prototyping a solution 80-90% is typically good enough. What you will learn also is that it takes 20% of your effort to reach 80% accuracy, and it takes 80% of your effort to address the remaining 20% of cases (the Pareto Principle). 

This is especially true in text analysis because the highly-skewed distribution of words and semantic structure (see \[Zipf's Law\](https://en.wikipedia.org/wiki/Zipf%27s_law) if you are curious). 

![The Power Law Distribution and the Harsh Reality of Language Learning –  Lucky's Notes](https://luckytoilet.wordpress.com/wp-content/uploads/2017/07/13.png?w=506&h=270)

**Comment by castower** [comment]
@CTNovoa @KaytieS 
Seconding @lecy's post, you'll want to set your rules to catch most instances of the titles that match the criteria.

Therefore when working with the text-based words you can consider what would be the most common words across numbers (ex two by itself and in twenty-two).

Recall from the regex cheatsheets (ex https://github.com/Watts-College/cpp-528-fall-2021/blob/main/lectures/RegExCheatsheetInR.pdf) that you can use anchors and grouping methods such as | (or) to identify substrings at the beginning, middle, and/or end of a string.

**Comment by CTNovoa** [comment]
Thank you, everyone! I think I have that down now. 

For some reason, I am having trouble with the "other" category (i.e., all other titles). I tried to use the NOT character (!), but can't see to quite place it correctly to work. Any advice would be appreciated! I also recognize I may be thinking about pulling "other" in the wrong way.

For example, I have been playing around with this:

Other <- (grepl("^![0-9]", d$title)|grepl("^!How", d$title)|grepl("!:", d$title)|grepl("!\\?$", d$title))

**Comment by castower** [comment]
@CTNovoa
You can save your titles from the other categories to character vectors and then filter all of the titles to not including those. 

You can do this with the titles themselves or the indices.

It may be helpful to think back to how you filtered out the unwanted goat/car in Lab 2.

**Comment by CTNovoa** [comment]
Thanks! I am noticing that Lab 01 and 02 solutions are locked--are we not able to look back at this time? I am reviewing my own labs, but I just wanted to ensure I went about it the right way. I appreciate all your help!

**Comment by castower** [comment]
@CTNovoa The Lab 1 solutions are locked, but Lab 2 should still be available. Are you unable to see them?

**Comment by CTNovoa** [comment]
When I click on the Lab02 solutions I get this error message: 
![image](https://github.com/user-attachments/assets/3b8855cd-67b9-415a-858c-3c1caf029980)

**Comment by castower** [comment]
@CTNovoa 
Ah, okay I updated the settings again. Try it now.

**Comment by CTNovoa** [comment]
Seems to be working now. Thank you, @castower !
