### ISSUE TITLE
Final Lab Part 1: Step 9

### ISSUE THREAD

**Issue by ClaudiaHebert** [Watts-College/paf-514-template#92]
@castower I'm a little unclear on what we're supposed to do for this step. Because there are so many academic units I'm figuring a loop is needed around this last bit of code (below) to create a graph for each individual unit of the university:

d %>%  
  filter( Department.Description == "Psychology" ) %>% 
  create_table( ) %>% 
  build_graph( unit="Psychology" )

Currently I have a loop that looks like this and doesn't run:
unique_departments <- unique(d$Department.Description)

for(i in unique_departments) {
d %>%  
  filter(Department.Description == i ) %>% 
  create_salary_table() %>% 
  build_graph(unit=i)
}

But I can't figure out where the create_table() function is coming from. At first I thought we were supposed to wrap add_position and build_graph into it but build_graph is already there and add_position is in build_graph. 

The test code build_graph( t.salary, unit="Psychology" ) also doesn't run.

Can you clarify? Thanks!

**Comment by bpiontek-asu** [comment]
@ClaudiaHebert, I think that the "create_table( )" function in the test code just needs to be updated to the "create_salary_table( )" function created in Part 1 Step 8.

@castower, like Claudia, I am having trouble getting the provided "build_graph( )" function to run, and am getting an error that reads:

> Error in UseMethod("filter") : 
  no applicable method for 'filter' applied to an object of class "NULL"

I've done some research around this error (honestly, I've been stuck at this step for about a day and can't figure out what my problem is, even after watching the video you posted last night, creating a new test file, and starting over with my code), and I came upon something on [Stack Overflow](https://stackoverflow.com/questions/72815138/error-in-usemethodfilter-no-applicable-method-for-filter-applied-to-an-o) that suggests that the issue is that the table that I want to filter is not loaded, but it appears to me that piping the data through the "create_salary_table( )" function the way that the test code does takes care of this, so I assume that's not my issue.

**Comment by ClaudiaHebert** [comment]
@bpiontek-asu Thanks for your response! I did try updating create_table() to the previously created create_salary_table() function in the loop cause I also eventually figured that's what that function was supposed to be.

I'm having the exact same issue as you though! I'm getting the same error when I try to run the test code with just build_graph() and also when I try to run the loop I shared above. Hoping @castower  has some insight cause I've been stuck here for a while too

**Comment by ClaudiaHebert** [comment]
@bpiontek-asu I think I figured it out! I'm not sure if you did the same but when I created the create_salary_table() function I had return(pander( t.salary )) as my return statement. This seemed to work fine when I assigned t.salary <- create_salary_table(d) and printed it directly but it created a null object. Removing the pander from the return statement seems to have fixed the issue.

**Comment by castower** [comment]
@ClaudiaHebert @bpiontek-asu 

You're correct, your create_table() function should be called `create_salary_table()`. You'll want to make sure you have the quarters in your data so you can then use them in the graphs.

You'll create your loop for all departments in Part II.

Let me know if you have any other questions!
